name: Deploy to CF Workers

on:
  push:
    branches:
      - 'content/*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Install Hugo
        run: sudo snap install hugo

      - name: Install Wrangler
        run: sudo npm i @cloudflare/wrangler -g

      - name: Build hugo minify gc
        run: hugo --minify --gc

      - name: Creatte wrangler.toml with name=blog and bucket=public
        run: wrangler init --site blog
        run: sed -i 's/bucket = ""/bucket = "public"/g' wrangler.toml
        run: export CF_API_TOKEN=${{ secrets.CF_API_TOKEN }}
        run: sed -i 's/account_id = ""/account_id = "'$CF_API_TOKEN'"/g' wrangler.toml
        run: echo wrangler.toml

      - name: config wrangler
        # run: CF_API_TOKEN=${{ secrets.CF_API_TOKEN }} wrangler publish
        run wrangler publish
